<div class="hn-widget">
    <div class="widget-header">
        <h3>Community Stats</h3></div>
    <div class="widget-body">
        <div class="d-flex flex-row flex-wrap">
            <div class="stats-box">
                <p>Followers</p>
                <h4>19.2K</h4></div>
            <div class="stats-box">
                <p>Total Posts</p>
                <h4>4.3K</h4></div>
        </div>
    </div>
</div>
<div class="hn-widget">
    <div class="widget-header">
        <h3>People</h3></div>
    <div class="widget-body">
        <div class="people-widget">
            <p>Active contributors</p>
            <div class="d-flex flex-row flex-wrap faces-list">
                <a href="https://hashnode.com/@alexi_be3" class="profile-pic author-pic drop-theme-arrows drop-target"><img data-sizes="auto" src="https://hashnode.imgix.net/res/hashnode/image/upload/v1526349616594/rJt4ypvRG.jpeg?w=70&amp;h=70&amp;fit=crop&amp;crop=faces&amp;auto=format,enhance&amp;q=60" data-src="https://hashnode.imgix.net/res/hashnode/image/upload/v1526349616594/rJt4ypvRG.jpeg?w=70&amp;h=70&amp;fit=crop&amp;crop=faces&amp;auto=format,enhance&amp;q=60" data-width="70" data-height="70" alt="Alexi Taylor  🚀's photo" class="lazyautosizes lazyloaded" sizes="32px"></a>
                <a href="https://hashnode.com/@krissanawat" class="profile-pic author-pic drop-theme-arrows drop-target"><img data-sizes="auto" src="https://hashnode.imgix.net/res/hashnode/image/upload/v1522628087543/HJe-Lx1jf.jpeg?w=70&amp;h=70&amp;fit=crop&amp;crop=faces&amp;auto=format,enhance&amp;q=60" data-src="https://hashnode.imgix.net/res/hashnode/image/upload/v1522628087543/HJe-Lx1jf.jpeg?w=70&amp;h=70&amp;fit=crop&amp;crop=faces&amp;auto=format,enhance&amp;q=60" data-width="70" data-height="70" alt="krissanawat's photo" class="lazyautosizes lazyloaded" sizes="32px"></a>
                <a href="https://hashnode.com/@siddharthkp" class="profile-pic author-pic drop-theme-arrows drop-target"><img data-sizes="auto" src="https://hashnode.imgix.net/res/hashnode/image/upload/v1539789182039/H1LFWREoX.jpeg?w=70&amp;h=70&amp;fit=crop&amp;crop=faces&amp;auto=format,enhance&amp;q=60" data-src="https://hashnode.imgix.net/res/hashnode/image/upload/v1539789182039/H1LFWREoX.jpeg?w=70&amp;h=70&amp;fit=crop&amp;crop=faces&amp;auto=format,enhance&amp;q=60" data-width="70" data-height="70" alt="Sid's photo" class="lazyautosizes lazyloaded" sizes="32px"></a>
                <a href="https://hashnode.com/@lorefnon" class="profile-pic author-pic drop-theme-arrows drop-target"><img data-sizes="auto" src="https://hashnode.imgix.net/res/hashnode/image/upload/uwz9rormkw6gfnnzloou/1453232392.jpg?w=70&amp;h=70&amp;fit=crop&amp;crop=faces&amp;auto=format,enhance&amp;q=60" data-src="https://hashnode.imgix.net/res/hashnode/image/upload/uwz9rormkw6gfnnzloou/1453232392.jpg?w=70&amp;h=70&amp;fit=crop&amp;crop=faces&amp;auto=format,enhance&amp;q=60" data-width="70" data-height="70" alt="Lorefnon's photo" class="lazyautosizes lazyloaded" sizes="32px"></a>
                <a href="https://hashnode.com/@spencercarli" class="profile-pic author-pic drop-theme-arrows drop-target"><img data-sizes="auto" src="https://hashnode.imgix.net/res/hashnode/image/upload/hcrb5jxyhvug0bgknesb_cropped/1507495539.png?w=70&amp;h=70&amp;fit=crop&amp;crop=faces&amp;auto=format,enhance&amp;q=60" data-src="https://hashnode.imgix.net/res/hashnode/image/upload/hcrb5jxyhvug0bgknesb_cropped/1507495539.png?w=70&amp;h=70&amp;fit=crop&amp;crop=faces&amp;auto=format,enhance&amp;q=60" data-width="70" data-height="70" alt="Spencer Carli's photo" class="lazyautosizes lazyloaded" sizes="32px"></a>
                <a href="https://hashnode.com/@andreianisimov" class="profile-pic author-pic drop-theme-arrows drop-target"><img data-sizes="auto" src="https://hashnode.imgix.net/res/hashnode/image/upload/v1556562116771/2wq5XFZXF.jpeg?w=70&amp;h=70&amp;fit=crop&amp;crop=faces&amp;auto=format,enhance&amp;q=60" data-src="https://hashnode.imgix.net/res/hashnode/image/upload/v1556562116771/2wq5XFZXF.jpeg?w=70&amp;h=70&amp;fit=crop&amp;crop=faces&amp;auto=format,enhance&amp;q=60" data-width="70" data-height="70" alt="Andrei Anisimov's photo" class="lazyautosizes lazyloaded" sizes="32px"></a>
                <a href="https://hashnode.com/@syncfusion" class="profile-pic author-pic drop-theme-arrows drop-target"><img data-sizes="auto" src="https://hashnode.imgix.net/res/hashnode/image/upload/v1556005065362/ml9YDyMPO.png?w=70&amp;h=70&amp;fit=crop&amp;crop=faces&amp;auto=format,enhance&amp;q=60" data-src="https://hashnode.imgix.net/res/hashnode/image/upload/v1556005065362/ml9YDyMPO.png?w=70&amp;h=70&amp;fit=crop&amp;crop=faces&amp;auto=format,enhance&amp;q=60" data-width="70" data-height="70" alt="Syncfusion's photo" class="lazyautosizes lazyloaded" sizes="32px"></a>
                <a href="https://hashnode.com/@sandeep" class="profile-pic author-pic drop-theme-arrows drop-target"><img data-sizes="auto" src="https://hashnode.imgix.net/res/hashnode/image/upload/v1546597615910/SyOxr3hbE.jpeg?w=70&amp;h=70&amp;fit=crop&amp;crop=faces&amp;auto=format,enhance&amp;q=60" data-src="https://hashnode.imgix.net/res/hashnode/image/upload/v1546597615910/SyOxr3hbE.jpeg?w=70&amp;h=70&amp;fit=crop&amp;crop=faces&amp;auto=format,enhance&amp;q=60" data-width="70" data-height="70" alt="Sandeep Panda's photo" class="lazyautosizes lazyloaded" sizes="32px"></a>
                <a href="https://hashnode.com/@go_diego" class="profile-pic author-pic drop-theme-arrows drop-target"><img data-sizes="auto" src="https://hashnode.imgix.net/res/hashnode/image/upload/v1554928060133/fYebP8n9L.jpeg?w=70&amp;h=70&amp;fit=crop&amp;crop=faces&amp;auto=format,enhance&amp;q=60" data-src="https://hashnode.imgix.net/res/hashnode/image/upload/v1554928060133/fYebP8n9L.jpeg?w=70&amp;h=70&amp;fit=crop&amp;crop=faces&amp;auto=format,enhance&amp;q=60" data-width="70" data-height="70" alt="Diego Bernal's photo" class="lazyautosizes lazyloaded" sizes="32px"></a>
                <a href="https://hashnode.com/@Ipseeta" class="profile-pic author-pic drop-theme-arrows drop-target"><img data-sizes="auto" src="https://hashnode.imgix.net/res/hashnode/image/upload/ismrtfybsrco3a4ftfas_cropped/1492538354.png?w=70&amp;h=70&amp;fit=crop&amp;crop=faces&amp;auto=format,enhance&amp;q=60" data-src="https://hashnode.imgix.net/res/hashnode/image/upload/ismrtfybsrco3a4ftfas_cropped/1492538354.png?w=70&amp;h=70&amp;fit=crop&amp;crop=faces&amp;auto=format,enhance&amp;q=60" data-width="70" data-height="70" alt="Ipseeta Priyadarshini's photo" class="lazyautosizes lazyloaded" sizes="32px"></a>
            </div><a href="#" class="see-all-button">See all</a></div>
    </div>
</div>